## Diet and Microbiome Predictors of Plasma Vitamin B12 in Healthy U.S. Adults
Scripts used in data wrangling and basic visualizations of vitamin B12 status, dietary, and metagenomic data 

## Step 1: clean rawFFQ data 
- input: CTSC24532USDAWHNRCNu_DATA_2021-06-07_1529.csv
- output: clean_FL100_FFQ.csv

## Step 2: check assumption and transform response variable 
- inputs: 1) clean_FL100_FFQ.csv 2) diet_data_AtLeast2atHomeRecallsQC.txt 3) 2024-08-16-FL100 B12 and folate results and Stnds and Utak.xlsx
- output: B12_with_BMI.csv

## Step 3: make comparisons between groups 
- inputs: 1) B12_with_BMI.csv 2) FL100_eGFR.csv
- outputs:1) taxaHFE_metadata.txt 2) taxaHFE_metadata_supplement_users.txt 3) taxaHFE_metadata_supplement_non_users.txt

## Step 4: correlate important taxa in metagenomes (identified by taxaHFE) with variables of interest 
- input: 1) taxaHFE_metadata.txt 2) merged_metaphlan_v4-0-6.txt
- output: 1) supplement_user_correlations.csv 2) supplement_non_user_correlations.csv
